[package]
name = "javascript_eval_native"
version = "0.4.0"
authors = ["tombatron <tommy.hanks@gmail.com>"]
edition = "2018"

[lib]
name="javascript_eval_native"
crate-type=["rlib", "dylib"]

[dependencies]
v8 = "0.63.0" # V8 Version 11.0.226.13
