[package]
name = "javascript_eval_native"
version = "0.3.0"
authors = ["tombatron <tommy.hanks@gmail.com>"]
edition = "2018"

[lib]
name="javascript_eval_native"
crate-type=["rlib", "dylib"]

[dependencies]
rusty_v8 = "0.25.3"
