name: Publish Linux Binary

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'
    - name: Build Rust Dependencies
      run: "${GITHUB_WORKSPACE}/build-nix.sh"
    - name: Build NuGet Package
      run: "nuget pack ${GITHUB_WORKSPACE}/src/nuget/JavaScript.Eval.x64-Linux-Native/JavaScript.Eval.x64-Linux-Native.nuspec"
    - name: Publish NuGet Package
      run: "nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${secrets.NUGET_API_KEY}"
